// Code generated by go-swagger; DO NOT EDIT.

// Package restapi blackbox
//
//  blackbox
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /api/v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - text/html
//    - application/json
//
// swagger:meta
package restapi
