// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "blackbox",
    "title": "blackbox",
    "version": "1.0.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/algorand/qrcodes": {
      "get": {
        "description": "GET Algorand redeem rewards QR code\n",
        "tags": [
          "crypto-checkout"
        ],
        "summary": "GET Algorand redeem rewards QR code",
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/CheckoutQRCode"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/checkout": {
      "post": {
        "description": "Post start checkout\n",
        "tags": [
          "crypto-checkout"
        ],
        "summary": "Post start checkout",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/CheckoutParams"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Checkout"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Checkout": {
      "type": "object",
      "properties": {
        "algorand_qrcode": {
          "$ref": "#/definitions/CheckoutQRCode"
        },
        "ref_id": {
          "description": "The unique reference id of the order",
          "type": "string"
        }
      }
    },
    "CheckoutParams": {
      "type": "object",
      "properties": {
        "line_items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/OrderLineItems"
          }
        }
      }
    },
    "CheckoutQRCode": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "integer",
          "format": "int64"
        },
        "base64_encoded_qr_code": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "properties": {
        "message": {
          "description": "A human-readable error message",
          "type": "string",
          "example": "You are not authorized to access this resource."
        }
      }
    },
    "OrderLineItems": {
      "type": "object",
      "properties": {
        "product_id": {
          "description": "The unique reference id of the product",
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "blackbox",
    "title": "blackbox",
    "version": "1.0.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/algorand/qrcodes": {
      "get": {
        "description": "GET Algorand redeem rewards QR code\n",
        "tags": [
          "crypto-checkout"
        ],
        "summary": "GET Algorand redeem rewards QR code",
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/CheckoutQRCode"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/checkout": {
      "post": {
        "description": "Post start checkout\n",
        "tags": [
          "crypto-checkout"
        ],
        "summary": "Post start checkout",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/CheckoutParams"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Checkout"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Checkout": {
      "type": "object",
      "properties": {
        "algorand_qrcode": {
          "$ref": "#/definitions/CheckoutQRCode"
        },
        "ref_id": {
          "description": "The unique reference id of the order",
          "type": "string"
        }
      }
    },
    "CheckoutParams": {
      "type": "object",
      "properties": {
        "line_items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/OrderLineItems"
          }
        }
      }
    },
    "CheckoutQRCode": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "integer",
          "format": "int64"
        },
        "base64_encoded_qr_code": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "properties": {
        "message": {
          "description": "A human-readable error message",
          "type": "string",
          "example": "You are not authorized to access this resource."
        }
      }
    },
    "OrderLineItems": {
      "type": "object",
      "properties": {
        "product_id": {
          "description": "The unique reference id of the product",
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
}
