// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CheckoutQRCode checkout q r code
//
// swagger:model CheckoutQRCode
type CheckoutQRCode struct {

	// amount
	Amount int64 `json:"amount,omitempty"`

	// base64 encoded qr code
	Base64EncodedQrCode string `json:"base64_encoded_qr_code,omitempty"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this checkout q r code
func (m *CheckoutQRCode) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this checkout q r code based on context it is used
func (m *CheckoutQRCode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CheckoutQRCode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CheckoutQRCode) UnmarshalBinary(b []byte) error {
	var res CheckoutQRCode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
