// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrderLineItems order line items
//
// swagger:model OrderLineItems
type OrderLineItems struct {

	// The unique reference id of the product
	ProductID string `json:"product_id,omitempty"`
}

// Validate validates this order line items
func (m *OrderLineItems) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this order line items based on context it is used
func (m *OrderLineItems) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderLineItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderLineItems) UnmarshalBinary(b []byte) error {
	var res OrderLineItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
